<a href="https://colab.research.google.com/github/Paolino1994/IntroIA/blob/main/Gu%C3%ADa%20de%20Ejercicios%202/PCA_en_NumPy_Guia_2_Ejercicio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Implementación de PCA en NumPy

## Objetivos
* Implementación de PCA en NumPy paso a paso
* Comparación de resultados con Scikit-learn

In [2]:
import numpy as np
from numpy.linalg import eig
from sklearn import decomposition

## Implementación

1. Dado un dataset $X \in \mathbb{R}^{n, d}$, con $n$ muestras y $d$ features, queremos reducir sus dimensiones a $m$. Para ello, el primer paso es centrar el dataset (Hint: usen np.mean)

In [3]:
# INSERTAR CÓDIGO AQUÍ
X = np.array( [ [0.8, 0.7] , [0.1, -0.1] ] )
X=X-X.mean()
X

array([[ 0.425,  0.325],
       [-0.275, -0.475]])

2. Obtener la matriz de covarianza de $X^T$, revisar en la teoría por qué utilizamos la transpuesta. Buscar en la documentación de NumPy qué funciones se pueden utilizar.

In [4]:
covXt=np.cov(np.transpose(X))

3. Calcular los autovalores y autovectores de la matriz de covarianza. Revisar la documentación de NumPy.

In [5]:
eigValues,eigVectors=eig(covXt)
eigValues,eigVectors


(array([0.   , 0.565]), array([[-0.75257669, -0.65850461],
        [ 0.65850461, -0.75257669]]))

4. Ordernar los autovectores en el sentido de los autovalores decrecientes, revisar la teoría de ser necesario.

In [6]:
# INSERTAR CÓDIGO AQUÍ
eigVectors=eigVectors[eigValues.argsort()]
eigValues=eigValues[eigValues.argsort()]

5. Proyectar el dataset centrado sobre los $m$ autovectores más relevantes (Hint: usen np.dot).

In [7]:
# INSERTAR CÓDIGO AQUÍ
P = eigVectors.T.dot(X.T)
P

array([[-0.1058311 , -0.1058311 ],
       [-0.52445188,  0.5385627 ]])

6. Consolidar los pasos anteriores en una función o clase PCA.

In [19]:
# INSERTAR CÓDIGO AQUÍ
def PCA(X):
  X=(X-np.mean(X,axis=0))/np.std(X,axis=0)
  #X=(X-np.mean(X,axis=0))
  covXt=np.cov(np.transpose(X))
  eigValues,eigVectors=eig(covXt)
  
  order=eigValues.argsort()[::-1]
  eigVectors=eigVectors[order]
  eigValues=eigValues[order]
  P = eigVectors.T.dot(X.T).T
  return P,eigValues,eigVectors

7. Comparar los resultados obtenidos con el modelo de PCA implementado en Scikit-learn ([ver documentación](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html)). Tomar como dataset:

$X=\begin{bmatrix}
0.8 & 0.7\\
0.1 & -0.1
\end{bmatrix}$

Se debe reducir a un componente. Verificar los resultados con np.testing.assert_allclose

In [56]:
# INSERTAR CÓDIGO AQUÍ
X = np.array( [ [0.8, 0.7] , [0.1, -0.1] ] )
custom=PCA(X)
pca=decomposition.PCA(n_components=2)
pcafitted=pca.fit_transform((X-np.mean(X,axis=0))/np.std(X,axis=0))

if np.allclose(-custom[0],pcafitted) or np.allclose(custom[0],pcafitted):
  print("Resultados iguales para ambas implementaciones")

Resultados iguales para ambas implementaciones
