<a href="https://colab.research.google.com/github/Paolino1994/IntroIA/blob/main/Gu%C3%ADa%20de%20Ejercicios%203/Guia_Clase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [140]:
import numpy as np
from sklearn import preprocessing

Ejecicio #1: Normalización

Muchos algoritmos de Machine Learning necesitan datos de entrada centrados y normalizados. Una normalización habitual es el z-score, que implica restarle la media y dividir por el desvío a cada feature de mi dataset.

In [141]:
def zScore(X):
  #X=np.array(X)
  mean=X.mean(axis=0)
  std=X.std(axis=0)
  return (X-mean)/std

In [142]:
X=np.array([1,80,3,55]).reshape(2,2)
scaler = preprocessing.StandardScaler().fit(X)
X_scaled = scaler.transform(X)
if(np.allclose(zScore(X),X_scaled)):
  print("Scaler is working Great")


Scaler is working Great


Ejecicio #2: Remover filas y columnas con NaNs en un dataset

Dado un dataset, hacer una función que, utilizando numpy, filtre las columnas y las filas que tienen NaNs.

In [143]:
def removeNANs(X):
  nonNANRows=~np.isnan(X).any(axis=0)
  X=X.T[nonNANRows].T
  nonNANColumns=~np.isnan(X).any(axis=1)
  X=X[nonNANColumns]
  return X

In [144]:
X=np.array([0,1,2,3,4,5,np.NaN,7,8]).reshape(3,3)
print(X)
removeNANs(X)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [nan  7.  8.]]


array([[1., 2.],
       [4., 5.],
       [7., 8.]])

Ejecicio #3: Reemplazar NaNs por la media de la columna

Dado un dataset, hacer una función que utilizando numpy reemplace los NaNs por la media de la columna.

In [145]:
def replaceNANs(X):
  means=np.nanmean(X, axis=0)
  Nans = np.where(np.isnan(X))
  X[Nans] = np.take(means, Nans[1]) 
  return X


In [146]:
X=np.array([0,1,2,3,4,5,np.NaN,7,8]).reshape(3,3)
replaceNANs(X)

array([[0. , 1. , 2. ],
       [3. , 4. , 5. ],
       [1.5, 7. , 8. ]])

Ejecicio #4: Dado un dataset X separarlo en 70 / 20 / 10

Como vimos en el ejercicio integrador, en problemas de Machine Learning es fundamental que separemos los datasets de n muestras, en 3 datasets de la siguiente manera:

    Training dataset: los datos que utilizaremos para entrenar nuestros modelos. Ej: 70% de las muestras.
    Validation dataset: los datos que usamos para calcular métricas y ajustar los hiperparámetros de nuestros modelos. Ej: 20% de las muestras.
    Testing dataset: una vez que entrenamos los modelos y encontramos los hiperparámetros óptimos de los mísmos, el testing dataset se lo utiliza para computar las métricas finales de nuestros modelos y analizar cómo se comporta respecto a la generalización. Ej: 10% de las muestras.

A partir de utilizar np.random.permutation, hacer un método que dado un dataset, devuelva los 3 datasets como nuevos numpy arrays.

In [149]:
def splitData(X):
  Xrand=np.random.permutation(X)
  trainQ=int(len(Xrand)*0.7)
  testQ=int(len(Xrand)*0.2)+trainQ
  valQ=len(Xrand)
  return Xrand[:trainQ],Xrand[trainQ:testQ],Xrand[testQ:valQ]

In [150]:
X=np.array(range(0,300)).reshape(100,3)
for i in splitData(X):
  print(i.shape)

(70, 3)
(20, 3)
(10, 3)
