<a href="https://colab.research.google.com/github/Paolino1994/IntroIA/blob/main/%20Gu%C3%ADa%20de%20Ejercicios%203/Guia_Clase_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
from sklearn import preprocessing

Ejecicio #1: Normalización

Muchos algoritmos de Machine Learning necesitan datos de entrada centrados y normalizados. Una normalización habitual es el z-score, que implica restarle la media y dividir por el desvío a cada feature de mi dataset.

In [29]:
def zScore(X):
  #X=np.array(X)
  mean=X.mean(axis=0)
  std=X.std(axis=0)
  return (X-mean)/std

In [36]:
X=np.array([1,80,3,55]).reshape(2,2)
scaler = preprocessing.StandardScaler().fit(X)
X_scaled = scaler.transform(X)
if(np.allclose(zScore(X),X_scaled)):
  print("Scaler is working Great")


True

Ejecicio #2: Remover filas y columnas con NaNs en un dataset

Dado un dataset, hacer una función que, utilizando numpy, filtre las columnas y las filas que tienen NaNs.

In [80]:
def removeNANs(X):
  nonNANRows=~np.isnan(X).any(axis=0)
  X=X.T[nonNANRows].T
  nonNANColumns=~np.isnan(X).any(axis=1)
  X=X[nonNANColumns]
  return X

In [81]:
X=np.array([0,1,2,3,4,5,np.NaN,7,8]).reshape(3,3)
print(X)
removeNANs(X)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [nan  7.  8.]]


array([[1., 2.],
       [4., 5.],
       [7., 8.]])

Ejecicio #3: Reemplazar NaNs por la media de la columna

Dado un dataset, hacer una función que utilizando numpy reemplace los NaNs por la media de la columna.

In [101]:
def replaceNANs(X):
  means=np.nanmean(X, axis=0)
  Nans = np.where(np.isnan(X))
  X[Nans] = np.take(means, Nans[1]) 
  return X


In [102]:
X=np.array([0,1,2,3,4,5,np.NaN,7,8]).reshape(3,3)
replaceNANs(X)

array([[0. , 1. , 2. ],
       [3. , 4. , 5. ],
       [1.5, 7. , 8. ]])

Ejecicio #4: Dado un dataset X separarlo en 70 / 20 / 10

Como vimos en el ejercicio integrador, en problemas de Machine Learning es fundamental que separemos los datasets de n muestras, en 3 datasets de la siguiente manera:

    Training dataset: los datos que utilizaremos para entrenar nuestros modelos. Ej: 70% de las muestras.
    Validation dataset: los datos que usamos para calcular métricas y ajustar los hiperparámetros de nuestros modelos. Ej: 20% de las muestras.
    Testing dataset: una vez que entrenamos los modelos y encontramos los hiperparámetros óptimos de los mísmos, el testing dataset se lo utiliza para computar las métricas finales de nuestros modelos y analizar cómo se comporta respecto a la generalización. Ej: 10% de las muestras.

A partir de utilizar np.random.permutation, hacer un método que dado un dataset, devuelva los 3 datasets como nuevos numpy arrays.

In [137]:
def splitData(X):
  Xrand=np.random.permutation(X)
  trainQ=int(len(Xrand)*0.7)
  testQ=int(len(Xrand)*0.2)+trainQ
  valQ=len(Xrand)
  print(trainQ,testQ,valQ)
  return Xrand[:trainQ],Xrand[trainQ:testQ],Xrand[testQ:valQ]

In [139]:
X=np.array(range(0,300)).reshape(100,3)

70 90 100
(70, 3)
[[141 142 143]
 [267 268 269]
 [105 106 107]
 [177 178 179]
 [234 235 236]
 [261 262 263]
 [288 289 290]
 [222 223 224]
 [198 199 200]
 [189 190 191]
 [111 112 113]
 [ 69  70  71]
 [147 148 149]
 [ 66  67  68]
 [225 226 227]
 [ 57  58  59]
 [ 33  34  35]
 [276 277 278]
 [249 250 251]
 [204 205 206]
 [129 130 131]
 [150 151 152]
 [195 196 197]
 [156 157 158]
 [ 90  91  92]
 [ 60  61  62]
 [162 163 164]
 [ 24  25  26]
 [144 145 146]
 [291 292 293]
 [ 63  64  65]
 [216 217 218]
 [252 253 254]
 [ 84  85  86]
 [153 154 155]
 [  3   4   5]
 [  9  10  11]
 [171 172 173]
 [273 274 275]
 [201 202 203]
 [240 241 242]
 [ 99 100 101]
 [246 247 248]
 [213 214 215]
 [159 160 161]
 [243 244 245]
 [ 36  37  38]
 [ 15  16  17]
 [120 121 122]
 [ 48  49  50]
 [ 39  40  41]
 [258 259 260]
 [180 181 182]
 [114 115 116]
 [ 30  31  32]
 [207 208 209]
 [ 93  94  95]
 [135 136 137]
 [126 127 128]
 [ 45  46  47]
 [237 238 239]
 [219 220 221]
 [168 169 170]
 [ 72  73  74]
 [285 286 287]
 [294 2